# Generated by Django 4.2.2 on 2023-07-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_person_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
