# Generated by Django 4.2.2 on 2023-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subject',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('HN', 'HINDI'), ('MT', 'MATHS')], max_length=2, null=True),
        ),
    ]
