# Generated by Django 4.2.2 on 2023-07-16 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_established', models.DateField(default=datetime.date.today)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.person')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='people',
            field=models.ManyToManyField(through='my_app.Relationship', to='my_app.person'),
        ),
    ]
