# Generated by Django 4.2.2 on 2023-07-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_family_relationship_family_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_app.person')),
                ('student_id', models.IntegerField()),
            ],
            bases=('my_app.person',),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['age']},
        ),
    ]
